# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev_colab/',
                'doc_host': 'https://muellerzr.github.io',
                'git_url': 'https://github.com/muellerzr/nbdev_colab/tree/master/',
                'lib_path': 'nbdev_colab'},
  'syms': {'nbdev_colab.core': {}, 'nbdev_colab.modules': {}}}
